name: Java CI with Maven

on:
  pull_request:
    branches:
      - main  # Déclenche l'action sur une PR vers la branche `main`

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de la dernière version d'Ubuntu pour exécuter l'action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone ton code dans l'environnement d'exécution

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # Installe JDK 11
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install  # Compile ton projet Maven

      - name: Run tests
        run: mvn test  # Lance les tests unitaires
