name: Java CI with Maven

on:
  push:
    branches:
      - main   # Cette action s'exécute sur la branche "main" chaque fois qu'un commit est effectué.
  pull_request:
    branches:
      - main   # Cette action s'exécute lors de la création d'une pull request pour la branche "main".

jobs:
  build:
    runs-on: ubuntu-latest   # Utilise la dernière version d'Ubuntu pour l'exécution du job.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   # Cette action clone ton code dans l'environnement d'exécution.

      - name: Set up JDK 23
        uses: actions/setup-java@v2   # Installe Java JDK 11
        with:
          java-version: '23'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install   # Compile et teste ton projet Maven.

      - name: Run tests
        run: mvn test   # Lance les tests automatisés de ton projet.
